version: '3.9'

services:
  backend1:
    image: asquare-backend
    container_name: backend1
    restart: always
    environment:
      DB_HOST: mysql-db
      DB_USER: asquare
      DB_PASSWORD: asquare123
      DB_NAME: asquare_exam

  backend2:
    image: asquare-backend
    container_name: backend2
    restart: always
    environment:
      DB_HOST: mysql-db
      DB_USER: asquare
      DB_PASSWORD: asquare123
      DB_NAME: asquare_exam

  backend3:
    image: asquare-backend
    container_name: backend3
    restart: always
    environment:
      DB_HOST: mysql-db
      DB_USER: asquare
      DB_PASSWORD: asquare123
      DB_NAME: asquare_exam

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asquare_exam
      MYSQL_USER: asquare
      MYSQL_PASSWORD: asquare123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: